version: '3.9'
name: wintercms

services:
  winter:
    build:
      context: ${PWD}
      dockerfile: winter/Dockerfile
      args:
        - WINTER_PREFIX=${WINTER_PREFIX:-/opt/infra7}
        - WINTER_PROJECT=${WINTER_PROJECT:-winter}
      tags:
        - infra7/wintercms:latest
        - infra7/wintercms:${WINTER_VERSION}-${TARGET_OS}
    environment:
      - WINTER_PREFIX=${WINTER_PREFIX:-/opt/infra7}
      - WINTER_PROJECT=${WINTER_PROJECT:-winter}
    image: infra7/wintercms:latest
    extends:
      file: volumes.yml
      service: winter
    ports:
      - 8008:8008

networks:
  default:
    name: ${WINTER_PROJECT}
